### ISSUE TITLE
Creating information on how do I annotate my data?

### ISSUE THREAD

**Issue by dorahermes** [bids-standard/bids-starter-kit#251]
It would be helpful to create a how-to page on how to use HED tags and SCORE tags.
Tagging @tpatpa 

- How can we store this information in a events.tsv scans.tsv and sessions.tsv
- Add link to BIDS examples

**Comment by Remi-Gau** [comment]
@VisLab is there any information about HED that belongs in the starter kit and / or should we "just" try to channel users towards the most relevant page in the HED documentation ?

Maybe a super light weight example in the starter kit?

**Comment by dorahermes** [comment]
The necessity for this was discussed today at the BEP21 extension proposal meeting. There is a request from BIDS users for this, and the starter kit is a good point to link/refer to the relevant documentation.

**Comment by VisLab** [comment]
Yes we should definitely do this as soon as possible.  If you suggest a place to put it, I will do a draft.

**Comment by dorahermes** [comment]
One option would be:
- Tutorials
   - Annotating data 

Annotating data can then include information for annotating events and include links to HED info. Reason for calling it Annotating data is that this term is what I would be looking for as a BIDS starter. 

@robertoostenveld and I also have ran into questions about annotations at the session and the scans levels and we can include sections describing those options here as well.

If we add information about e.g. annotating artifacts in data and link to the [SCORE HED schema library ](https://github.com/hed-standard/hed-schema-library), we should make clear that this is WIP and recommendations can be made as issues on that github page.

**Comment by VisLab** [comment]
Okay I am getting ready to write a tutorial on annotating data.  Most of the tutorials that currently exist in the starter kit link to other places.  I think the annotating data should probably part of a Bids-starter kit series rather than putting a tutorial on the HED site (although this could be done too if that is preferred).  

Where should the tutorial be hosted?  If on the BIDS starter-kit site, is there a particular "style"?   I could do it in the standard readthedocs format to start, but would appreciate some guidance here. @dorahermes @Remi-Gau

**Comment by Remi-Gau** [comment]
I believe this can now be closed.

Thanks @VisLab for that excellent new page. Sorry I did not take the time to review it, but reading now I realize how I much I need this in my life. :-)
