### ISSUE TITLE
Broken link in community resource

### ISSUE THREAD

**Issue by KirstieJane** [bids-standard/bids-starter-kit#75]
I don't know what type of file the [Graphical Representation of BIDS](https://drive.google.com/drive/folders/1xlfeAFpp8iOH12bXONfD9OsRGLFFSLD-) (Brainhack NYC 2018, NY USA - N Markowitz (2018)) should be. (It's part of the [community resources](https://github.com/INCF/BIDS-Starter-Kit/wiki/community-resources) in the wiki). When I download the file it doesn't have a suffix and I don't know what programme to open it in!

**Comment by Park-Patrick** [comment]
This is the source tweet of that link: https://twitter.com/AkiNikolaidis/status/991718858749874176

Seems like it has to be opened in draw.io (a google drive extension), so I'll note that beside the link

**Comment by KirstieJane** [comment]
Aaah - great! Yes - now I can open it there :)

@sportnoah14 - are you the creator of this image? I love it! It looks like there's a way to embed it into an iframe or publish it to the web - what do you think about us integrating that kind of viewing here?

**Comment by sportnoah14** [comment]
Hello, yes I did make this. I'm glad you like it. This is an initial attempt at trying to visualize and understand the BIDS structure. I in fact did imbed it in a website I created for that event [link here](https://sportnoah14.github.io/Brainhack_large_data_project/). I've been slow at this but have given thought to expanding it to a more professional app. If you think it's a good idea and others might be interested, then I can get more serious about it and get started. Otherwise, I can make some instructions on how you can create your own version of this graph

**Comment by Park-Patrick** [comment]
Hi @sportnoah14 I find the visualization super helpful! 

If you do find time to expand the app more or write up the instructions, give us a ping or feel free to add it to the [community resources](https://github.com/INCF/BIDS-Starter-Kit/wiki/community-resources) 👍

**Comment by Remi-Gau** [comment]
closing as obsolete
