### ISSUE TITLE
Adding matlab code to read acquisition parameters from BIDS data set

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-starter-kit#88]
I had in mind to write up a couple of matlab functions to create reports of acquisition details contained in a BIDS data set. A bit like pybids does: https://github.com/INCF/pybids/tree/master/bids/reports.
Hope that no one has anything against it.
Had a quick look and to avoid reinventing the wheel, it will most likely will need to reuse some SPM functions (e.g SPM_BIDS and its dependencies) to make it work even if users don't have SPM installed.
I suspect that we don't want to constrain users to rely on a specific software but I guess it also make sense to reuse things that have been done before. 
What's your take?

**Comment by Remi-Gau** [comment]
yup exactly

**Comment by gllmflndn** [comment]
Hi @Remi-Gau,
``spm_BIDS`` relies on a small set of SPM functions so it would be possible to make a standalone version; I would also be happy to get some help to develop it further (e.g. more aligned with ``pybids``).
That's something I already did this for the JSON library used here: https://github.com/gllmflndn/JSONio
Backward compatibility with old MATLAB releases and compatibility with Octave are a requirement for me so ``table`` and ``writetable`` cannot be used yet; SPM has ``spm_load`` and ``spm_save`` for this.

**Comment by Remi-Gau** [comment]
See #91 for a first attempt that reads anat and func

**Comment by gllmflndn** [comment]
Thanks @Remi-Gau, seems like we emailed each other at the same time...
I only had so far a brief look at #91 and I will comment there but I think it would be easier in a first instance if you don't include all of the SPM dependencies so that we can focus on the new features to start with. Concerning the inheritance principle in `spm_BIDS` , there is still work to do but I would recommend you use the query functionality instead of accessing the content of the `BIDS` variable directly, see:
https://www.wikibooks.org/wiki/SPM/BIDS#BIDS_parser_and_queries
If you need to access information that cannot be obtained through a query then we will have to modify `spm_BIDS` to make that happen.

**Comment by Remi-Gau** [comment]
Yup I was just thinking that I was still trying to reinvent the wheel rather than trying to use the "query" functionality of spm_BIDS. Will modify accordingly.
WRT SPM dependencies: I will work on it with the latest version of SPM in my path and then see how this can be incorporated in the BIDS starter kit.

**Comment by KirstieJane** [comment]
Hey @gllmflndn & @Remi-Gau - is this issue ready to close?

**Comment by gllmflndn** [comment]
I think so, given that #91 has been merged.
In the meantime, spm_BIDS moved in a new repository: https://github.com/bids-standard/bids-matlab
It would make sense to move Remi's function there as +bids/report.m

**Comment by Remi-Gau** [comment]
will move it here. Should I also do a PR to remove it from the bids-starter-kit repo?

**Comment by Remi-Gau** [comment]
Will leave the function there and only keep working on the one at https://github.com/bids-standard/bids-matlab.
Will make a PR that simply mentions this in the help section of the function on the BIDS starter kit repo.
